#!/usr/bin/python3
import subprocess
from typing import NamedTuple


class System(NamedTuple):
    fs: str
    size: str
    used: str
    avail: str
    use_percent: str
    mounted_on: str


def get_gb(v: str) -> int:
    return int(float(v.replace('G', '')))


def main() -> int:

    memory = subprocess.run(
            ('df', '-h'),
            capture_output=True,
            text=True,
        )
    memory_l = memory.stdout.strip().splitlines()
    systems = [System(*s.strip().split()) for s in memory_l[1:]]
    system = next((s for s in systems if s.mounted_on == '/'))

    try:
        swap = subprocess.run(
                ['swapon', '--show'],
                capture_output=True,
                text=True,
            )
        swap_str = swap.stdout.split('\n')[1].split()[2].replace('G', '')
        swap_value = int(float(swap_str.replace(',', '.')))
    except FileNotFoundError:
        swap_value = 0

    total = get_gb(system.size)
    used = get_gb(system.used)
    print(f"{used - swap_value}G/{total - swap_value}G")
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
