#!/usr/bin/python


import subprocess

memory = subprocess.run(['df', '-h'], capture_output=True, text=True)
memory = memory.stdout
memory = memory.split('\n')[3]

try:
    swap = subprocess.run(
            ['swapon', '--show'],
            capture_output=True,
            text=True,
        )
    swap = swap.stdout.split('\n')[1].split()[2].replace('G', '')
    swap = int(swap)
except FileNotFoundError:
    swap = 0
_, total, used, avail, _, _ = memory.replace('G', '').split()
total = int(total)
used = int(used)
print(f"{used - swap}G/{total - swap}G")
