#!/usr/bin/python3


import subprocess
import shlex
import os

load_average = os.getloadavg()[0]

cores_number = os.cpu_count()

load = float(load_average) / cores_number * 100

temp = None
command= subprocess.run('sensors', capture_output=True, text=True) 
for line in command.stdout.split('\n'):
    if line.startswith('Package id 0'):
        temp = line.split()[3].replace('+', '')

if temp is None:
    print(f'{round(load)}%')
else:
    print(f'{round(load)}%/{temp}')
