#!/usr/bin/python


import subprocess
import shlex

load_average = subprocess.run('uptime', capture_output=True, text=True)
load_average = load_average.stdout.split(',')[2].split()[-1].replace(',', '.')

cores_number = subprocess.run(
        shlex.split('cat /proc/cpuinfo | grep -c processor'),
        capture_output=True, text=True)

ps = subprocess.run(shlex.split('cat /proc/cpuinfo'), check=True, capture_output=True)
cores_number = subprocess.run(
        shlex.split('grep -c processor'),
        input=ps.stdout, 
        capture_output=True)
cores_number = int(cores_number.stdout.decode().strip())

load = float(load_average) / cores_number * 100

command= subprocess.run('sensors', capture_output=True, text=True) 
for line in command.stdout.split('\n'):
    if line.startswith('Package id 0'):
        temp = line.split()[3].replace('+', '')

print(f'{round(load)}%/{temp}')  # type: ignore
